### ISSUE TITLE
UnicodeEncodeErrors

### ISSUE THREAD

**Issue by lalelunet** [SpamExperts/pyzor#132]
### Version information
1.0.0

There are several characters that are not recognized and result in a error

I do not have the mails that produce this errors. You can see the unknown character in the log. The last log occured often without the info of the character

Do I had to install a plugin for character encoding?

Regards

`﻿
2022-04-09 07:07:50.631247500 Apr  9 07:07:50.631 [2814] warn: internal error, python traceback seen in response: Traceback (most recent call last):\n File "/usr/bin/pyzor", line 408, in <module>\n main()\n File "/usr/bin/pyzor", line 152, in main\n if not dispatch(client, servers, config):\n File "/usr/bin/pyzor", line 237, in check\n for digested in get_input_handler(style):\n File "/usr/bin/pyzor", line 175, in _get_input_msg\n digested = digester(msg).value\n File "/usr/lib/python3.9/site-packages/pyzor/digest.py", line 82, in __init__\n for payload in self.digest_payloads(msg):\n File "/usr/lib/python3.9/site-packages/pyzor/digest.py", line 149, in digest_payloads\n payload = part.get_payload(decode=True)\n File "/usr/lib/python3.9/email/message.py", line 264, in get_payload\n bpayload = payload.encode('ascii', 'surrogateescape')\nUnicodeEncodeError: 'ascii' codec can't encode character '\xf3' in position 752: ordinal not in range(128) at /usr/share/perl5/vendor_perl/Mail/SpamAssassin/Plugin/Pyzor.pm line 308.
2022-04-10 00:49:14.334277500 Apr 10 00:49:14.334 [7871] warn: internal error, python traceback seen in response: Traceback (most recent call last):\n File "/usr/bin/pyzor", line 408, in <module>\n main()\n File "/usr/bin/pyzor", line 152, in main\n if not dispatch(client, servers, config):\n File "/usr/bin/pyzor", line 237, in check\n for digested in get_input_handler(style):\n File "/usr/bin/pyzor", line 175, in _get_input_msg\n digested = digester(msg).value\n File "/usr/lib/python3.9/site-packages/pyzor/digest.py", line 82, in __init__\n for payload in self.digest_payloads(msg):\n File "/usr/lib/python3.9/site-packages/pyzor/digest.py", line 149, in digest_payloads\n payload = part.get_payload(decode=True)\n File "/usr/lib/python3.9/email/message.py", line 264, in get_payload\n bpayload = payload.encode('ascii', 'surrogateescape')\nUnicodeEncodeError: 'ascii' codec can't encode character '\xdc' in position 679: ordinal not in range(128) at /usr/share/perl5/vendor_perl/Mail/SpamAssassin/Plugin/Pyzor.pm line 308.
2022-04-10 07:23:24.772426500 Apr 10 07:23:24.772 [8262] warn: internal error, python traceback seen in response: Traceback (most recent call last):\n File "/usr/bin/pyzor", line 408, in <module>\n main()\n File "/usr/bin/pyzor", line 152, in main\n if not dispatch(client, servers, config):\n File "/usr/bin/pyzor", line 237, in check\n for digested in get_input_handler(style):\n File "/usr/bin/pyzor", line 175, in _get_input_msg\n digested = digester(msg).value\n File "/usr/lib/python3.9/site-packages/pyzor/digest.py", line 82, in __init__\n for payload in self.digest_payloads(msg):\n File "/usr/lib/python3.9/site-packages/pyzor/digest.py", line 149, in digest_payloads\n payload = part.get_payload(decode=True)\n File "/usr/lib/python3.9/email/message.py", line 264, in get_payload\n bpayload = payload.encode('ascii', 'surrogateescape')\nUnicodeEncodeError: 'ascii' codec can't encode character '\xdf' in position 594: ordinal not in range(128) at /usr/share/perl5/vendor_perl/Mail/SpamAssassin/Plugin/Pyzor.pm line 308.
2022-04-10 16:46:02.504769500 Apr 10 16:46:02.505 [12299] warn: internal error, python traceback seen in response: Traceback (most recent call last):\n File "/usr/bin/pyzor", line 408, in <module>\n main()\n File "/usr/bin/pyzor", line 152, in main\n if not dispatch(client, servers, config):\n File "/usr/bin/pyzor", line 237, in check\n for digested in get_input_handler(style):\n File "/usr/bin/pyzor", line 175, in _get_input_msg\n digested = digester(msg).value\n File "/usr/lib/python3.9/site-packages/pyzor/digest.py", line 82, in __init__\n for payload in self.digest_payloads(msg):\n File "/usr/lib/python3.9/site-packages/pyzor/digest.py", line 149, in digest_payloads\n payload = part.get_payload(decode=True)\n File "/usr/lib/python3.9/email/message.py", line 264, in get_payload\n bpayload = payload.encode('ascii', 'surrogateescape')\nUnicodeEncodeError: 'ascii' codec can't encode character '\xe8' in position 563: ordinal not in range(128) at /usr/share/perl5/vendor_perl/Mail/SpamAssassin/Plugin/Pyzor.pm line 308.
2022-04-10 11:17:33.910064500 Apr 10 11:17:33.910 [10327] warn: internal error, python traceback seen in response: Traceback (most recent call last):\n File "/usr/bin/pyzor", line 408, in <module>\n main()\n File "/usr/bin/pyzor", line 152, in main\n if not dispatch(client, servers, config):\n File "/usr/bin/pyzor", line 237, in check\n for digested in get_input_handler(style):\n File "/usr/bin/pyzor", line 175, in _get_input_msg\n digested = digester(msg).value\n File "/usr/lib/python3.9/site-packages/pyzor/digest.py", line 82, in __init__\n for payload in self.digest_payloads(msg):\n File "/usr/lib/python3.9/site-packages/pyzor/digest.py", line 149, in digest_payloads\n payload = part.get_payload(decode=True)\n File "/usr/lib/python3.9/email/message.py", line 264, in get_payload\n bpayload = payload.encode('ascii', 'surrogateescape')\nUnicodeEncodeError: 'ascii' codec can't encode character '\xc4' in position 643: ordinal not in range(128) at /usr/share/perl5/vendor_perl/Mail/SpamAssassin/Plugin/Pyzor.pm line 308.
2022-04-10 01:03:46.918444500 Apr 10 01:03:46.918 [7871] warn: internal error, python traceback seen in response: Traceback (most recent call last):\n File "/usr/bin/pyzor", line 408, in <module>\n main()\n File "/usr/bin/pyzor", line 152, in main\n if not dispatch(client, servers, config):\n File "/usr/bin/pyzor", line 237, in check\n for digested in get_input_handler(style):\n File "/usr/bin/pyzor", line 175, in _get_input_msg\n digested = digester(msg).value\n File "/usr/lib/python3.9/site-packages/pyzor/digest.py", line 82, in __init__\n for payload in self.digest_payloads(msg):\n File "/usr/lib/python3.9/site-packages/pyzor/digest.py", line 149, in digest_payloads\n payload = part.get_payload(decode=True)\n File "/usr/lib/python3.9/email/message.py", line 264, in get_payload\n bpayload = payload.encode('ascii', 'surrogateescape')\nUnicodeEncodeError: 'ascii' codec can't encode character '\xf4' in position 558: ordinal not in range(128) at /usr/share/perl5/vendor_perl/Mail/SpamAssassin/Plugin/Pyzor.pm line 308.
2022-04-10 12:02:07.066673500 Apr 10 12:02:07.067 [10704] warn: internal error, python traceback seen in response: Traceback (most recent call last):\n File "/usr/bin/pyzor", line 408, in <module>\n main()\n File "/usr/bin/pyzor", line 152, in main\n if not dispatch(client, servers, config):\n File "/usr/bin/pyzor", line 237, in check\n for digested in get_input_handler(style):\n File "/usr/bin/pyzor", line 175, in _get_input_msg\n digested = digester(msg).value\n File "/usr/lib/python3.9/site-packages/pyzor/digest.py", line 82, in __init__\n for payload in self.digest_payloads(msg):\n File "/usr/lib/python3.9/site-packages/pyzor/digest.py", line 149, in digest_payloads\n payload = part.get_payload(decode=True)\n File "/usr/lib/python3.9/email/message.py", line 264, in get_payload\n bpayload = payload.encode('ascii', 'surrogateescape')\nUnicodeEncodeError: 'ascii' codec can't encode character '\u2020' in position 667: ordinal not in range(128) at /usr/share/perl5/vendor_perl/Mail/SpamAssassin/Plugin/Pyzor.pm line 308.
2022-04-10 13:02:46.918245500 Apr 10 13:02:46.918 [11079] warn: internal error, python traceback seen in response: Traceback (most recent call last):\n File "/usr/bin/pyzor", line 408, in <module>\n main()\n File "/usr/bin/pyzor", line 152, in main\n if not dispatch(client, servers, config):\n File "/usr/bin/pyzor", line 237, in check\n for digested in get_input_handler(style):\n File "/usr/bin/pyzor", line 175, in _get_input_msg\n digested = digester(msg).value\n File "/usr/lib/python3.9/site-packages/pyzor/digest.py", line 82, in __init__\n for payload in self.digest_payloads(msg):\n File "/usr/lib/python3.9/site-packages/pyzor/digest.py", line 149, in digest_payloads\n payload = part.get_payload(decode=True)\n File "/usr/lib/python3.9/email/message.py", line 264, in get_payload\n bpayload = payload.encode('ascii', 'surrogateescape')\nUnicodeEncodeError: 'ascii' codec can't encode character '\u2013' in position 667: ordinal not in range(128) at /usr/share/perl5/vendor_perl/Mail/SpamAssassin/Plugin/Pyzor.pm line 308.
2022-04-10 14:39:54.393396500 Apr 10 14:39:54.393 [11518] warn: internal error, python traceback seen in response: Traceback (most recent call last):\n File "/usr/bin/pyzor", line 408, in <module>\n main()\n File "/usr/bin/pyzor", line 152, in main\n if not dispatch(client, servers, config):\n File "/usr/bin/pyzor", line 237, in check\n for digested in get_input_handler(style):\n File "/usr/bin/pyzor", line 175, in _get_input_msg\n digested = digester(msg).value\n File "/usr/lib/python3.9/site-packages/pyzor/digest.py", line 82, in __init__\n for payload in self.digest_payloads(msg):\n File "/usr/lib/python3.9/site-packages/pyzor/digest.py", line 149, in digest_payloads\n payload = part.get_payload(decode=True)\n File "/usr/lib/python3.9/email/message.py", line 264, in get_payload\n bpayload = payload.encode('ascii', 'surrogateescape')\nUnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 622: ordinal not in range(128) at /usr/share/perl5/vendor_perl/Mail/SpamAssassin/Plugin/Pyzor.pm line 308.
2022-04-10 19:22:01.188707500 Apr 10 19:22:01.189 [13116] warn: internal error, python traceback seen in response: Traceback (most recent call last):\n File "/usr/bin/pyzor", line 408, in <module>\n main()\n File "/usr/bin/pyzor", line 152, in main\n if not dispatch(client, servers, config):\n File "/usr/bin/pyzor", line 237, in check\n for digested in get_input_handler(style):\n File "/usr/bin/pyzor", line 175, in _get_input_msg\n digested = digester(msg).value\n File "/usr/lib/python3.9/site-packages/pyzor/digest.py", line 82, in __init__\n for payload in self.digest_payloads(msg):\n File "/usr/lib/python3.9/site-packages/pyzor/digest.py", line 149, in digest_payloads\n payload = part.get_payload(decode=True)\n File "/usr/lib/python3.9/email/message.py", line 264, in get_payload\n bpayload = payload.encode('ascii', 'surrogateescape')\nUnicodeEncodeError: 'ascii' codec can't encode character '\xa9' in position 1499: ordinal not in range(128) at /usr/share/perl5/vendor_perl/Mail/SpamAssassin/Plugin/Pyzor.pm line 308.
2022-04-11 00:10:48.543574500 Apr 11 00:10:48.543 [14301] warn: internal error, python traceback seen in response: Traceback (most recent call last):\n File "/usr/bin/pyzor", line 408, in <module>\n main()\n File "/usr/bin/pyzor", line 152, in main\n if not dispatch(client, servers, config):\n File "/usr/bin/pyzor", line 237, in check\n for digested in get_input_handler(style):\n File "/usr/bin/pyzor", line 175, in _get_input_msg\n digested = digester(msg).value\n File "/usr/lib/python3.9/site-packages/pyzor/digest.py", line 82, in __init__\n for payload in self.digest_payloads(msg):\n File "/usr/lib/python3.9/site-packages/pyzor/digest.py", line 149, in digest_payloads\n payload = part.get_payload(decode=True)\n File "/usr/lib/python3.9/email/message.py", line 264, in get_payload\n bpayload = payload.encode('ascii', 'surrogateescape')\nUnicodeEncodeError: 'ascii' codec can't encode character '\xc7' in position 545: ordinal not in range(128) at /usr/share/perl5/vendor_perl/Mail/SpamAssassin/Plugin/Pyzor.pm line 308.
2022-04-11 05:31:45.669343500 Apr 11 05:31:45.669 [15076] warn: internal error, python traceback seen in response: Traceback (most recent call last):\n File "/usr/bin/pyzor", line 408, in <module>\n main()\n File "/usr/bin/pyzor", line 152, in main\n if not dispatch(client, servers, config):\n File "/usr/bin/pyzor", line 237, in check\n for digested in get_input_handler(style):\n File "/usr/bin/pyzor", line 175, in _get_input_msg\n digested = digester(msg).value\n File "/usr/lib/python3.9/site-packages/pyzor/digest.py", line 82, in __init__\n for payload in self.digest_payloads(msg):\n File "/usr/lib/python3.9/site-packages/pyzor/digest.py", line 149, in digest_payloads\n payload = part.get_payload(decode=True)\n File "/usr/lib/python3.9/email/message.py", line 264, in get_payload\n bpayload = payload.encode('ascii', 'surrogateescape')\nUnicodeEncodeError: 'ascii' codec can't encode character '\xf6' in position 648: ordinal not in range(128) at /usr/share/perl5/vendor_perl/Mail/SpamAssassin/Plugin/Pyzor.pm line 308.
2022-04-11 09:03:16.659261500 Apr 11 09:03:16.659 [16726] warn: internal error, python traceback seen in response: Traceback (most recent call last):\n File "/usr/bin/pyzor", line 408, in <module>\n main()\n File "/usr/bin/pyzor", line 152, in main\n if not dispatch(client, servers, config):\n File "/usr/bin/pyzor", line 237, in check\n for digested in get_input_handler(style):\n File "/usr/bin/pyzor", line 175, in _get_input_msg\n digested = digester(msg).value\n File "/usr/lib/python3.9/site-packages/pyzor/digest.py", line 82, in __init__\n for payload in self.digest_payloads(msg):\n File "/usr/lib/python3.9/site-packages/pyzor/digest.py", line 149, in digest_payloads\n payload = part.get_payload(decode=True)\n File "/usr/lib/python3.9/email/message.py", line 264, in get_payload\n bpayload = payload.encode('ascii', 'surrogateescape')\nUnicodeEncodeError: 'ascii' codec can't encode character '\xfc' in position 655: ordinal not in range(128) at /usr/share/perl5/vendor_perl/Mail/SpamAssassin/Plugin/Pyzor.pm line 308.
2022-04-11 10:31:59.724912500 Apr 11 10:31:59.725 [17641] warn: internal error, python traceback seen in response: Traceback (most recent call last):\n File "/usr/bin/pyzor", line 408, in <module>\n main()\n File "/usr/bin/pyzor", line 152, in main\n if not dispatch(client, servers, config):\n File "/usr/bin/pyzor", line 237, in check\n for digested in get_input_handler(style):\n File "/usr/bin/pyzor", line 175, in _get_input_msg\n digested = digester(msg).value\n File "/usr/lib/python3.9/site-packages/pyzor/digest.py", line 82, in __init__\n for payload in self.digest_payloads(msg):\n File "/usr/lib/python3.9/site-packages/pyzor/digest.py", line 149, in digest_payloads\n payload = part.get_payload(decode=True)\n File "/usr/lib/python3.9/email/message.py", line 264, in get_payload\n bpayload = payload.encode('ascii', 'surrogateescape')\nUnicodeEncodeError: 'ascii' codec can't encode character '\xe4' in position 600: ordinal not in range(128) at /usr/share/perl5/vendor_perl/Mail/SpamAssassin/Plugin/Pyzor.pm line 308.
2022-04-11 05:05:13.374379500 Apr 11 05:05:13.374 [14691] warn: internal error, python traceback seen in response: Traceback (most recent call last):\n File "/usr/bin/pyzor", line 408, in <module>\n main()\n File "/usr/bin/pyzor", line 152, in main\n if not dispatch(client, servers, config):\n File "/usr/bin/pyzor", line 237, in check\n for digested in get_input_handler(style):\n File "/usr/bin/pyzor", line 175, in _get_input_msg\n digested = digester(msg).value\n File "/usr/lib/python3.9/site-packages/pyzor/digest.py", line 82, in __init__\n for payload in self.digest_payloads(msg):\n File "/usr/lib/python3.9/site-packages/pyzor/digest.py", line 149, in digest_payloads\n payload = part.get_payload(decode=True)\n File "/usr/lib/python3.9/email/message.py", line 264, in get_payload\n bpayload = payload.encode('ascii', 'surrogateescape')\nUnicodeEncodeError: 'ascii' codec can't encode character '\xa0' in position 644: ordinal not in range(128) at /usr/share/perl5/vendor_perl/Mail/SpamAssassin/Plugin/Pyzor.pm line 308.

2022-04-10 23:55:28.131404500 Apr 10 23:55:28.131 [14301] warn: internal error, python traceback seen in response: Traceback (most recent call last):\n File "/usr/bin/pyzor", line 408, in <module>\n main()\n File "/usr/bin/pyzor", line 152, in main\n if not dispatch(client, servers, config):\n File "/usr/bin/pyzor", line 237, in check\n for digested in get_input_handler(style):\n File "/usr/bin/pyzor", line 175, in _get_input_msg\n digested = digester(msg).value\n File "/usr/lib/python3.9/site-packages/pyzor/digest.py", line 82, in __init__\n for payload in self.digest_payloads(msg):\n File "/usr/lib/python3.9/site-packages/pyzor/digest.py", line 149, in digest_payloads\n payload = part.get_payload(decode=True)\n File "/usr/lib/python3.9/email/message.py", line 264, in get_payload\n bpayload = payload.encode('ascii', 'surrogateescape')\nUnicodeEncodeError: 'ascii' codec can't encode characters in position 582-585: ordinal not in range(128) at /usr/share/perl5/vendor_perl/Mail/SpamAssassin/Plugin/Pyzor.pm line 308.

`

**Comment by sidney** [comment]
This looks like Python bug https://github.com/python/cpython/issues/94606 that I recently reported and have submitted a PR for. The problem is in the Python email.message.get_payload function which raises UnicodeEncodeError if it encounters email message content in a non-multipart text/* message that contains certain problematic Unicode characters.

I'm not one of the Pyzor developers. I don't know how much of a workaround is possible before it eventually gets fixed and released in Python, or whether the fix will be backported to older versions of Python. It may be possible to wrap a try around the call to  get_payload in Pyzor and do something to keep processing the email, but that's outside og my expertise.

I am one of the SpamAssassin developes, but at the moment I don't have any ideas for handling this there other than making sure that the failure in Pyzor doesn't affect anything else processing that email.
