### ISSUE TITLE
Error digesting badly formed message (decode() argument 1 must be string without null bytes)

### ISSUE THREAD

**Issue by tonyandrewmeyer** [SpamExperts/pyzor#40]
~ # pyzor check < 1ZKiRG-0007ja-DV--7132194856063680649
    Traceback (most recent call last):
      File "/usr/local/bin/pyzor", line 408, in <module>
        main()
      File "/usr/local/bin/pyzor", line 152, in main
        if not dispatch(client, servers, config):
      File "/usr/local/bin/pyzor", line 237, in check
        for digested in get_input_handler(style):
      File "/usr/local/bin/pyzor", line 175, in _get_input_msg
        digested = digester(msg).value
      File "/usr/local/lib/python2.7/site-packages/pyzor/digest.py", line 82, in __init__
        for payload in self.digest_payloads(msg):
      File "/usr/local/lib/python2.7/site-packages/pyzor/digest.py", line 160, in digest_payloads
        payload = payload.decode(charset, errors)
    TypeError: decode() argument 1 must be string without null bytes, not str

Probably something to do with this:

    Content-Type: text/plain;
        charset="iso-8859-1^@^@^@Content-Transfer-Encoding: quoted-printable

---

We need to remove any '\x00' (NULL characters) when processing messages.

**Comment by tonyandrewmeyer** [comment]
Annoying not being able to attach a file.  I can't use gist because it doesn't like the nulls.  I'll email it to you.

**Comment by alexkiro** [comment]
I've attached the message here in [zip file](https://github.com/SpamExperts/pyzor/files/80011/1ZKiRG-0007ja-DV--7132194856063680649.zip)

**Comment by GabiSL** [comment]
Verified - Passed!
