### ISSUE TITLE
exec of latest head FAILs: 'TypeError: write() argument must be str, not bytes'

### ISSUE THREAD

**Issue by pgnd** [SpamExperts/pyzor#75]
building latest head causes exex FAIL,

```
cd /usr/local/src/pyzor
git reset --hard
git log | head
	commit 751ab3f7490f0fe5d5be2a7d4154d3bd2f9d622b
	Author: Cosmin Grozea <cosmin.grozea94@gmail.com>
	Date:   Wed Oct 31 11:26:57 2018 +0200

	    Refs. #68

	    Catch `OSError` when Pyzor cannot create homedir. This can be prevented if we use `--homedir` option

	commit bd5ad2b1d070975755745023d4da5aa8e0dbf813
	Author: Tony Meyer <tony@spamexperts.com>

python3 -V
	Python 3.6.5
python3 setup.py build
python3 setup.py install
pyzor -V
	Traceback (most recent call last):
	  File "/usr/bin/pyzor", line 4, in <module>
	    __import__('pkg_resources').run_script('pyzor==1.1.0', 'pyzor')
	  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 750, in run_script
	    self.require(requires)[0].run_script(script_name, ns)
	  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1534, in run_script
	    exec(script_code, namespace, namespace)
	  File "/usr/lib/python3.6/site-packages/pyzor-1.1.0-py3.6.egg/EGG-INFO/scripts/pyzor", line 433, in <module>
	  File "/usr/lib/python3.6/site-packages/pyzor-1.1.0-py3.6.egg/EGG-INFO/scripts/pyzor", line 135, in main
	  File "/usr/lib/python3.6/site-packages/pyzor-1.1.0-py3.6.egg/EGG-INFO/scripts/pyzor", line 94, in load_configuration
	  File "/usr/lib64/python3.6/codecs.py", line 377, in write
	    self.stream.write(data)
	TypeError: write() argument must be str, not bytes
```

Dropping back to prior rev fixes the issue,
```
git reset --hard 2b8d76d6b86ea2e9076a9c34ffd4651909d214b7
	git log | head
	commit 2b8d76d6b86ea2e9076a9c34ffd4651909d214b7
	Author: cosmin.g <cosmin.grozea94@gmail.com>
	Date:   Wed May 9 12:35:23 2018 +0300

	    Refs. #63
	     * Add missing `\n` in procmail recipes

	commit f173edfced753e4129c06b8239d7105a16df95b9
	Author: Tony Meyer <tony@spamexperts.com>
	Date:   Sat Feb 10 00:10:37 2018 +1300

python3 setup.py build
python3 setup.py install
pyzor -V
	/usr/bin/pyzor 1.1.0
```

**Comment by kubbity** [comment]
Verified.
```
root@server1:~/pyzor# pyzor -V
/usr/local/bin/pyzor 1.1.0
```
